[package]
name = "momonga"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = "0.2"
lazy_static = "1.4.0"
pest = "2.6"
pest_derive = "2.6"

[dependencies.web-sys]
version = "0.3"
features = [
    "Window",
    "CustomEvent"
]
